tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  
  - name: terraform-cli
    before: |
      cd /workspace
      wget "https://releases.hashicorp.com/terraform/$(curl -sL https://releases.hashicorp.com/terraform/ | grep -oP 'terraform/[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | cut -d/ -f2)/terraform_$(curl -sL https://releases.hashicorp.com/terraform/ | grep -oP 'terraform/[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | cut -d/ -f2)_linux_amd64.zip"
      unzip terraform_*.zip -d /usr/local/bin
      terraform --version
